name = "go-view-hono"
main = "src/index.ts"
compatibility_date = "2024-12-17"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
# MY_VAR = "my-variable"
BUCKET_NAME = "go-view"
PROJECT_COUNT_LIMIT= 2
# 24 * 60 * 60
JWT_EXPIRES=86400
TOKEN_NAME = 'goViewHonoToken'

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "go-view"

[[d1_databases]]
binding = "DB"
database_name = "go-view"
database_id = "fdb6b816-f05c-471e-9ff3-7cd6d52fadde"


# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
